services:
  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_HOST=${DATABASE_HOST}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    ports:
      - '3307:3306'
    networks:
      - app-network

  backend:
    image: node:20-buster
    ports:
      - '3001:3000' # 백엔드 포트
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - TZ=${TZ}
      - CHOKIDAR_USEPOLLING=true
    tty: true
    volumes:
      - ./project_nest-deployment-repo:/app
    working_dir: /app
    command: >
      bash -c "npm install && npm run start:dev"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    image: node:22
    ports:
      - '5173:5173' # 프론트엔드 포트
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    volumes:
      - ./project_react-deployment-repo:/app
    working_dir: /app
    command: >
      bash -c "npm install && npm run dev"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysqldata: